services:
  
  elasticsearch-6:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.23
    container_name: elasticsearch-6
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9206:9200"
    networks:
      - elastic-network
   
  kibana-6:
    image: docker.elastic.co/kibana/kibana:6.8.23
    container_name: kibana-6
    ports:
      - "5606:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch-6:9200
    networks:
      - elastic-network
    depends_on:
      - elasticsearch-6
networks:
  elastic-network:
    driver: bridge